In [7]:
import pandas as pd

movies = pd.read_csv(
    "movies.dat",
    sep="::",
    engine="python",
    encoding="latin1",
    header=None,
    names=["movie_id", "title", "genres"]
)

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [14]:
movies['genres'] = movies['genres'].str.split("|")

In [15]:
movies.head()

,movie_id,title,genres
0,1,Toy Story (1995),"[Animation, Children's, Comedy]"
1,2,Jumanji (1995),"[Adventure, Children's, Fantasy]"
2,3,Grumpier Old Men (1995),"[Comedy, Romance]"
3,4,Waiting to Exhale (1995),"[Comedy, Drama]"
4,5,Father of the Bride Part II (1995),[Comedy]

In [8]:
import pandas as pd

ratings = pd.read_csv(
    "ratings.dat",
    sep="::",
    engine="python",
    encoding="latin1",
    header=None,
    names=["user_id", "movie_id", "rating", "timestamp"]
)

ratings.head()

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [9]:
import pandas as pd

users = pd.read_csv(
    "users.dat",
    sep="::",
    engine="python",
    encoding="latin1",
    header=None,
    names=["user_id", "gender", "age", "occupation", "zip_code"]
)

users.head()

   user_id gender  age  occupation zip_code
0        1      F    1          10    48067
1        2      M   56          16    70072
2        3      M   25          15    55117
3        4      M   45           7    02460
4        5      M   25          20    55455

In [10]:
age_map = {
    1: "Under 18",
    18: "18-24",
    25: "25-34",
    35: "35-44",
    45: "45-49",
    50: "50-55",
    56: "56+"
}

users["age_group"] = users["age"].map(age_map)

In [11]:
occupation_map = {
    0: "other",
    1: "academic/educator",
    2: "artist",
    3: "clerical/admin",
    4: "college/grad student",
    5: "customer service",
    6: "doctor/health care",
    7: "executive/managerial",
    8: "farmer",
    9: "homemaker",
    10: "K-12 student",
    11: "lawyer",
    12: "programmer",
    13: "retired",
    14: "sales/marketing",
    15: "scientist",
    16: "self-employed",
    17: "technician/engineer",
    18: "tradesman/craftsman",
    19: "unemployed",
    20: "writer"
}

users["occupation_name"] = users["occupation"].map(occupation_map)

In [12]:
users.head()

   user_id gender  age  occupation zip_code age_group       occupation_name
0        1      F    1          10    48067  Under 18          K-12 student
1        2      M   56          16    70072       56+         self-employed
2        3      M   25          15    55117     25-34             scientist
3        4      M   45           7    02460     45-49  executive/managerial
4        5      M   25          20    55455     25-34                writer